<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\OficinaAuth.Dominio\OficinaAuth.Dominio.csproj" />
  </ItemGroup>
  <ItemGroup>
    <!-- Mesma versao da stack que VALIDA o token no oficina-app (Oficina.Api.csproj). -->
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.22.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.22.0" />
  </ItemGroup>
</Project>
