<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <!-- Lambda: o handler e o nome do assembly executavel. -->
    <AssemblyName>OficinaAuth.Api</AssemblyName>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OficinaAuth.Infraestrutura\OficinaAuth.Infraestrutura.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer.Hosting" Version="2.2.1" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="OficinaAuth.Api.Testes" />
  </ItemGroup>
</Project>
